In [1]:
import numpy as np
import torch
import torchvision
import torch.nn as nn
import torch.nn.functional as F
from torchvision import transforms
from torchvision.datasets import MNIST
from torch.utils.data.dataloader import DataLoader
from torch.utils.data.sampler import SubsetRandomSampler

In [2]:
datasets = MNIST(root = 'classification data/', download = True)

In [3]:
datasets = MNIST(root = 'classification data/', train = True)

In [4]:
len(datasets)

60000

In [5]:
test_data = MNIST(root = 'classification data/', train = False)

In [6]:
len(test_data)

10000

In [7]:
datasets[2]

(<PIL.Image.Image image mode=L size=28x28 at 0x1DA960DAA08>, 4)

In [8]:
test_data[200]

(<PIL.Image.Image image mode=L size=28x28 at 0x1DA96101088>, 3)

In [9]:
datasets = MNIST(root = 'classification data/', train = True, transform = transforms.ToTensor())

In [10]:
img, label = datasets[2]
print(img.shape)
print(label)

torch.Size([1, 28, 28])
4


In [11]:
test_data = MNIST(root = 'classification data/', train = False, transform = transforms.ToTensor())

In [12]:
img, label = datasets[200]
print(img.shape)
print(label)

torch.Size([1, 28, 28])
1


In [13]:
# creating training datasets and validation datasets
def indices_selector(factor, data_num):
    val_num_of_indices = int(factor * data_num)
    total_indices = np.random.permutation(data_num)
    return total_indices[val_num_of_indices:], total_indices[:val_num_of_indices]

In [14]:
indices_selector(0.2, len(datasets))

(array([43977, 44013, 58357, ..., 16876, 27883, 17875]),
 array([ 9270, 21259, 40454, ..., 28492, 33663, 27840]))

In [15]:
train_indices, val_indices = indices_selector(0.2, len(datasets))

In [16]:
batch_size = 500

In [17]:
train_sampler = SubsetRandomSampler(train_indices)
train_data = DataLoader(datasets, batch_size, sampler = train_sampler)
val_sampler = SubsetRandomSampler(val_indices)
val_data = DataLoader(datasets, batch_size, sampler = val_sampler)

In [18]:
for x, y in train_data:
    print(x.shape)
#     print(y)
# print(x)

torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([50

In [19]:
input_size = 28*28
ouput_classes = 10

In [20]:
#creating model
class MNIST_Classifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(input_size, ouput_classes)
        
    def forward(self, input_reshape):
        input_reshape = input_reshape.reshape(-1, 28*28)
        output = self.linear(input_reshape)
        return output

In [21]:
model = MNIST_Classifier()

In [22]:
for image, label in train_data:
    output = model(image)
    print(output[:2])
    real_output = F.softmax(output, dim = 1)
    print(real_output)
    print(output.shape)

)
tensor([[0.1133, 0.0890, 0.0977,  ..., 0.0996, 0.0758, 0.0869],
        [0.1090, 0.0888, 0.0864,  ..., 0.1033, 0.0844, 0.0956],
        [0.1269, 0.0905, 0.0948,  ..., 0.1127, 0.0818, 0.0945],
        ...,
        [0.1107, 0.0946, 0.0950,  ..., 0.1165, 0.0890, 0.0892],
        [0.1093, 0.0982, 0.1042,  ..., 0.1132, 0.0744, 0.0842],
        [0.0844, 0.0688, 0.1224,  ..., 0.1309, 0.0651, 0.0929]],
       grad_fn=<SoftmaxBackward>)
torch.Size([500, 10])
tensor([[ 0.0234, -0.0928,  0.0643,  0.0270, -0.0086, -0.1224, -0.0767,  0.2786,
         -0.1293, -0.1425],
        [ 0.0597,  0.0318, -0.0655,  0.0368,  0.0936,  0.0927,  0.0801, -0.0132,
         -0.2604, -0.1650]], grad_fn=<SliceBackward>)
tensor([[0.1034, 0.0921, 0.1077,  ..., 0.1335, 0.0888, 0.0876],
        [0.1067, 0.1037, 0.0941,  ..., 0.0992, 0.0774, 0.0852],
        [0.1100, 0.1020, 0.1086,  ..., 0.1287, 0.0685, 0.0778],
        ...,
        [0.1100, 0.0635, 0.0930,  ..., 0.1287, 0.0728, 0.0808],
        [0.1134, 0.0992, 0.1022

In [23]:
real_output = F.softmax(output, dim = 1)

In [24]:
real_output

tensor([[0.1203, 0.0979, 0.1006,  ..., 0.1142, 0.0799, 0.0834],
        [0.1084, 0.1052, 0.1057,  ..., 0.1078, 0.0704, 0.1014],
        [0.1272, 0.0824, 0.0791,  ..., 0.1029, 0.0881, 0.0865],
        ...,
        [0.1381, 0.0892, 0.0796,  ..., 0.1147, 0.0852, 0.0933],
        [0.0932, 0.0850, 0.1036,  ..., 0.1265, 0.0853, 0.0849],
        [0.1023, 0.0645, 0.0810,  ..., 0.1405, 0.0803, 0.0862]],
       grad_fn=<SoftmaxBackward>)

In [25]:
print(torch.sum(real_output[:5]).item())

5.0


In [26]:
best_prob, pred = torch.max(real_output, dim = 1)
# print(best_prob)
print(pred[:50])
print("REAL LABELS")
print(label[:50])

tensor([0, 0, 0, 6, 0, 0, 7, 6, 6, 6, 0, 0, 7, 6, 2, 6, 6, 0, 7, 6, 3, 7, 0, 7,
        6, 7, 6, 6, 6, 0, 6, 6, 7, 5, 7, 6, 0, 7, 4, 6, 0, 7, 7, 4, 5, 7, 7, 7,
        6, 2])
REAL LABELS
tensor([9, 1, 5, 5, 7, 6, 4, 9, 4, 2, 8, 4, 8, 2, 1, 3, 6, 3, 7, 2, 3, 0, 8, 8,
        2, 9, 8, 1, 3, 6, 6, 2, 8, 6, 7, 9, 2, 9, 9, 6, 7, 7, 8, 4, 6, 3, 0, 6,
        6, 9])


In [27]:
#creating evaluation metric and loss function
def accuracy(predicted, actual_label):
    return torch.sum(predicted == actual_label).item() / len(predicted)

accuracy(pred, label)


0.124

In [28]:

def loss_fn(pred, label):
    loss_fn  = F.cross_entropy
    loss = loss_fn(pred, label)
    return loss

In [29]:
optim = torch.optim.SGD(model.parameters(), lr = 0.002)

In [30]:
# Training
def train_loss(model, loss_fn,  train_dl, optimizer = None, metric = None):
    for image, label in train_dl:
        pred = model(image)
        loss = loss_fn(pred, label)
        # real_output = F.softmax(pred)
        best_prob, pred = torch.max(pred, dim = 1)
        
        if optimizer is not None:
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()

        metric_result = None
        if metric is not None:
            metric_result = metric(pred, label)

        return loss.item(), len(image), metric_result



In [31]:
train_loss(model, loss_fn,  train_data, optimizer = optim, metric = accuracy)

(2.297713041305542, 500, 0.13)

In [32]:
def val_loss(model, loss_fn, val_dl, metric = None):
    losses = []

    with torch.no_grad():
        for image, label in val_dl:
            pred = model(image)
            loss = loss_fn(pred, label)
            losses.append(loss)
            # real_output = F.softmax(pred)
            best_prob, pred = torch.max(real_output, dim = 1)

            # final_loss = sum(losses).item()/len(image))

            metric_result = None
            if metric is not None:
                metric_result = metric(pred, label)

            return  loss.item(), len(image), metric_result


In [33]:
val_loss(model, loss_fn, val_data, metric = accuracy)

(2.3038790225982666, 500, 0.09)

In [34]:
def fit(epochs, model, loss_fn,  train_dl, val_dl, optimizer = None, metric = None):
    for epoch in range(epochs):
        train_loss(model, loss_fn,  train_dl, optimizer = None, metric = accuracy)

        loss, total_len, metric_result = val_loss(model, loss_fn, val_dl, metric  = accuracy)

        print('{}/{}, {}, {}'.format(epoch +1 , epochs, loss, metric_result))

In [36]:
fit(5, model, loss_fn,  train_data, val_data, optimizer = optim, metric = accuracy)

1/5, 2.2939298152923584, 0.096
2/5, 2.2914860248565674, 0.088
3/5, 2.297717332839966, 0.086
4/5, 2.2920732498168945, 0.082
5/5, 2.296963691711426, 0.1


In [62]:
# Feedforward network
class MNIST_Feedforward(nn.Module):
    def __init__(self):
        super().__init__()
        self.net1 = nn.Linear(784, 128)
        self.net2 = nn.Linear(128, 10)

    def forward(self, image):
        image = image.view(image.size(0), -1)
        # image = image.reshape(-1, 28*28)
        image = F.relu(self.net1(image))
        image = F.relu(self.net2(image))
        return image

In [63]:
model = MNIST_Feedforward()

In [73]:
for x, y in train_data:
    pred = model(x)
    loss = loss_fn(pred, label)
    print(loss.item())
    break

2.302446126937866


In [76]:
for parameter in model.parameters():
    print(parameter.shape)

torch.Size([128, 784])
torch.Size([128])
torch.Size([10, 128])
torch.Size([10])


In [78]:
# GPU
torch.cuda.is_available()

False