In [1]:
import numpy as np
import torch
import torchvision
import torch.nn as nn
import torch.nn.functional as F
from torchvision import transforms
from torchvision.datasets import MNIST
from torch.utils.data.dataloader import DataLoader
from torch.utils.data.sampler import SubsetRandomSampler

In [2]:
datasets = MNIST(root = 'classification data/', download = True)

In [3]:
datasets = MNIST(root = 'classification data/', train = True)

In [4]:
len(datasets)

60000

In [5]:
test_data = MNIST(root = 'classification data/', train = False)

In [6]:
len(test_data)

10000

In [7]:
datasets[2]

(<PIL.Image.Image image mode=L size=28x28 at 0x2476676C848>, 4)

In [8]:
test_data[200]

(<PIL.Image.Image image mode=L size=28x28 at 0x2476676CEC8>, 3)

In [9]:
datasets = MNIST(root = 'classification data/', train = True, transform = transforms.ToTensor())

In [10]:
img, label = datasets[2]
print(img.shape)
print(label)

torch.Size([1, 28, 28])
4


In [11]:
test_data = MNIST(root = 'classification data/', train = False, transform = transforms.ToTensor())

In [12]:
img, label = datasets[200]
print(img.shape)
print(label)

torch.Size([1, 28, 28])
1


In [13]:
# creating training datasets and validation datasets
def indices_selector(factor, data_num):
    val_num_of_indices = int(factor * data_num)
    total_indices = np.random.permutation(data_num)
    return total_indices[val_num_of_indices:], total_indices[:val_num_of_indices]

In [14]:
indices_selector(0.2, len(datasets))

(array([25754, 46850, 51876, ..., 36453,  5762, 40766]),
 array([58696,  1996, 31233, ..., 37664, 45198, 14809]))

In [15]:
train_indices, val_indices = indices_selector(0.2, len(datasets))

In [16]:
batch_size = 500

In [17]:
train_sampler = SubsetRandomSampler(train_indices)
train_data = DataLoader(datasets, batch_size, sampler = train_sampler)
val_sampler = SubsetRandomSampler(val_indices)
val_data = DataLoader(datasets, batch_size, sampler = val_sampler)

In [18]:
for x, y in train_data:
    print(x.shape)
#     print(y)
# print(x)

torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([50

In [19]:
input_size = 28*28
ouput_classes = 10

In [20]:
#creating model
class MNIST_Classifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(input_size, ouput_classes)
        
    def forward(self, input_reshape):
        input_reshape = input_reshape.reshape(-1, 28*28)
        output = self.linear(input_reshape)
        return output

In [21]:
model = MNIST_Classifier()

In [22]:
for image, label in train_data:
    output = model(image)
    print(output[:2])
    real_output = F.softmax(output, dim = 1)
    print(real_output)
    print(output.shape)

tensor([[ 0.1149,  0.0211,  0.1823,  0.0847, -0.0243, -0.3073,  0.0557, -0.0672,
          0.0948, -0.0189],
        [ 0.3257,  0.1209, -0.3104, -0.1339,  0.0470, -0.2373, -0.1734, -0.0805,
          0.4467,  0.1262]], grad_fn=<SliceBackward>)
tensor([[0.1098, 0.1000, 0.1175,  ..., 0.0915, 0.1076, 0.0961],
        [0.1329, 0.1083, 0.0704,  ..., 0.0886, 0.1500, 0.1089],
        [0.1005, 0.1065, 0.1189,  ..., 0.0965, 0.0891, 0.1028],
        ...,
        [0.1212, 0.1356, 0.1049,  ..., 0.1026, 0.0857, 0.1037],
        [0.1023, 0.1161, 0.1191,  ..., 0.1020, 0.1089, 0.0964],
        [0.1361, 0.1081, 0.0851,  ..., 0.0852, 0.1276, 0.1138]],
       grad_fn=<SoftmaxBackward>)
torch.Size([500, 10])
tensor([[ 0.3017, -0.2825,  0.2248, -0.0121,  0.1627,  0.0320,  0.2738,  0.1736,
          0.2988,  0.0709],
        [ 0.3213,  0.2590,  0.3136, -0.1498,  0.1132, -0.4655,  0.0044,  0.1887,
          0.1982, -0.1211]], grad_fn=<SliceBackward>)
tensor([[0.1178, 0.0657, 0.1090,  ..., 0.1036, 0.1174, 0.0

In [23]:
real_output = F.softmax(output, dim = 1)

In [24]:
real_output

tensor([[0.1294, 0.1031, 0.1242,  ..., 0.0909, 0.0977, 0.0725],
        [0.1082, 0.0840, 0.1263,  ..., 0.1143, 0.0949, 0.0866],
        [0.1356, 0.0802, 0.0970,  ..., 0.1038, 0.1095, 0.0802],
        ...,
        [0.0933, 0.1191, 0.1081,  ..., 0.1355, 0.1140, 0.0878],
        [0.1347, 0.0578, 0.0825,  ..., 0.0867, 0.1254, 0.1244],
        [0.1237, 0.0863, 0.1050,  ..., 0.0966, 0.1118, 0.0960]],
       grad_fn=<SoftmaxBackward>)

In [25]:
print(torch.sum(real_output[:5]).item())

5.0


In [26]:
best_prob, pred = torch.max(real_output, dim = 1)
# print(best_prob)
print(pred[:50])
print("REAL LABELS")
print(label[:50])

tensor([0, 2, 0, 9, 2, 7, 3, 2, 1, 3, 0, 8, 0, 2, 0, 8, 8, 0, 0, 9, 0, 8, 0, 0,
        0, 0, 0, 0, 3, 0, 2, 6, 6, 8, 0, 9, 8, 0, 2, 6, 6, 8, 0, 7, 1, 8, 2, 0,
        8, 0])
REAL LABELS
tensor([4, 0, 0, 8, 8, 4, 3, 7, 2, 7, 6, 2, 5, 5, 7, 6, 3, 4, 9, 8, 3, 5, 4, 5,
        0, 9, 6, 2, 7, 2, 1, 9, 9, 3, 4, 0, 4, 0, 4, 8, 7, 7, 3, 9, 2, 4, 1, 7,
        2, 3])


In [27]:
#creating evaluation metric and loss function
def accuracy(predicted, actual_label):
    return torch.sum(predicted == actual_label).item() / len(predicted)

accuracy(pred, label)


0.116

In [28]:

def loss_fn(pred, label):
    loss_fn  = F.cross_entropy
    loss = loss_fn(pred, label)
    return loss

In [29]:
optim = torch.optim.SGD(model.parameters(), lr = 0.002)

In [30]:
# Training
def train_loss(model, loss_fn,  train_dl, optimizer = None, metric = None):
    for image, label in train_dl:
        pred = model(image)
        loss = loss_fn(pred, label)
        # real_output = F.softmax(pred)
        best_prob, pred = torch.max(pred, dim = 1)
        
        if optimizer is not None:
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()

        metric_result = None
        if metric is not None:
            metric_result = metric(pred, label)

        return loss.item(), len(image), metric_result



In [31]:
train_loss(model, loss_fn,  train_data, optimizer = optim, metric = accuracy)

(2.3203680515289307, 500, 0.136)

In [32]:
def val_loss(model, loss_fn, val_dl, metric = None):
    losses = []

    with torch.no_grad():
        for image, label in val_dl:
            pred = model(image)
            loss = loss_fn(pred, label)
            losses.append(loss)
            # real_output = F.softmax(pred)
            best_prob, pred = torch.max(real_output, dim = 1)

            # final_loss = sum(losses).item()/len(image))

            metric_result = None
            if metric is not None:
                metric_result = metric(pred, label)

            return  loss.item(), len(image), metric_result


In [33]:
val_loss(model, loss_fn, val_data, metric = accuracy)

(2.323425769805908, 500, 0.114)

In [34]:
def fit(epochs, model, loss_fn,  train_dl, val_dl, optimizer = None, metric = None):
    for epoch in range(epochs):
        train_loss(model, loss_fn,  train_dl, optimizer = None, metric = accuracy)

        loss, total_len, metric_result = val_loss(model, loss_fn, val_dl, metric  = accuracy)

        print('{}/{}, {}, {}'.format(epoch +1 , epochs, loss, metric_result))

In [35]:
fit(5, model, loss_fn,  train_data, val_data, optimizer = optim, metric = accuracy)

1/5, 2.330198049545288, 0.128
2/5, 2.3276844024658203, 0.11
3/5, 2.3311502933502197, 0.09
4/5, 2.3421566486358643, 0.088
5/5, 2.3391714096069336, 0.09


In [36]:
# Feedforward network
class MNIST_Feedforward(nn.Module):
    def __init__(self):
        super().__init__()
        self.net1 = nn.Linear(784, 128)
        self.net2 = nn.Linear(128, 10)

    def forward(self, image):
        image = image.view(image.size(0), -1)
        # image = image.reshape(-1, 28*28)
        image = F.relu(self.net1(image))
        image = F.relu(self.net2(image))
        return image

In [37]:
model = MNIST_Feedforward()

In [38]:
for x, y in train_data:
    pred = model(x)
    loss = loss_fn(pred, label)
    print(loss.item())
    break

2.307706832885742


In [39]:
for parameter in model.parameters():
    print(parameter.shape)

torch.Size([128, 784])
torch.Size([128])
torch.Size([10, 128])
torch.Size([10])


In [40]:
# GPU
torch.cuda.is_available()

False

In [42]:
# for x,y in train_data:
#     x = x.to('cuda')
#     y = y.to('cuda')
# print(x.device)
# print(y.device)

In [ ]:
# def get_default_device():
#     if torch.cuda.is_available():
#         return torch.device('cuda')
#     else:
#         return torch.device('cpu')