In [1]:
import numpy as np
import torch
import torchvision
import torch.nn as nn
import torch.nn.functional as F
from torchvision import transforms
from torchvision.datasets import MNIST
from torch.utils.data.dataloader import DataLoader
from torch.utils.data.sampler import SubsetRandomSampler

In [2]:
datasets = MNIST(root = 'classification data/', download = True)

In [3]:
datasets = MNIST(root = 'classification data/', train = True)

In [4]:
len(datasets)

60000

In [5]:
test_data = MNIST(root = 'classification data/', train = False)

In [6]:
len(test_data)

10000

In [7]:
datasets[2]

(<PIL.Image.Image image mode=L size=28x28 at 0x23BD0DFBC48>, 4)

In [8]:
test_data[200]

(<PIL.Image.Image image mode=L size=28x28 at 0x23BD0DFD688>, 3)

In [9]:
datasets = MNIST(root = 'classification data/', train = True, transform = transforms.ToTensor())

In [10]:
img, label = datasets[2]
print(img.shape)
print(label)

torch.Size([1, 28, 28])
4


In [11]:
test_data = MNIST(root = 'classification data/', train = False, transform = transforms.ToTensor())

In [12]:
img, label = datasets[200]
print(img.shape)
print(label)

torch.Size([1, 28, 28])
1


In [13]:
# creating training datasets and validation datasets
def indices_selector(factor, data_num):
    val_num_of_indices = int(factor * data_num)
    total_indices = np.random.permutation(data_num)
    return total_indices[val_num_of_indices:], total_indices[:val_num_of_indices]

In [14]:
indices_selector(0.2, len(datasets))

(array([34819, 47330,  5048, ..., 51918, 10369, 36881]),
 array([28554, 48301, 32924, ..., 46228,  3826, 41026]))

In [15]:
train_indices, val_indices = indices_selector(0.2, len(datasets))

In [16]:
batch_size = 500

In [17]:
train_sampler = SubsetRandomSampler(train_indices)
train_data = DataLoader(datasets, batch_size, sampler = train_sampler)
val_sampler = SubsetRandomSampler(val_indices)
val_data = DataLoader(datasets, batch_size, sampler = val_sampler)

In [18]:
for x, y in train_data:
    print(x.shape)
#     print(y)
# print(x)

torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([50

In [19]:
input_size = 28*28
ouput_classes = 10

In [20]:
#creating model
class MNIST_Classifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(input_size, ouput_classes)
        
    def forward(self, input_reshape):
        input_reshape = input_reshape.reshape(-1, 28*28)
        output = self.linear(input_reshape)
        return output

In [21]:
model = MNIST_Classifier()

In [22]:
for image, label in train_data:
    output = model(image)
    print(output[:2])
    real_output = F.softmax(output, dim = 1)
    print(real_output)
    print(output.shape)

20, 0.0928,  ..., 0.1016, 0.1147, 0.0841],
        [0.1087, 0.1272, 0.1383,  ..., 0.0705, 0.1020, 0.1013],
        ...,
        [0.1083, 0.1008, 0.0881,  ..., 0.1050, 0.0870, 0.1139],
        [0.1069, 0.1056, 0.0979,  ..., 0.0889, 0.1082, 0.0882],
        [0.0791, 0.1131, 0.0802,  ..., 0.1296, 0.1039, 0.1176]],
       grad_fn=<SoftmaxBackward>)
torch.Size([500, 10])
tensor([[ 0.1282, -0.0764,  0.0938,  0.5633, -0.1752,  0.1409, -0.1626,  0.0081,
          0.3205,  0.0129],
        [-0.0241,  0.1781, -0.0860,  0.1596, -0.1070, -0.0374, -0.0952, -0.0614,
          0.0791,  0.1951]], grad_fn=<SliceBackward>)
tensor([[0.1019, 0.0830, 0.0984,  ..., 0.0904, 0.1235, 0.0908],
        [0.0950, 0.1163, 0.0893,  ..., 0.0916, 0.1054, 0.1183],
        [0.0913, 0.0922, 0.0954,  ..., 0.0908, 0.1152, 0.1119],
        ...,
        [0.1000, 0.0987, 0.1043,  ..., 0.1046, 0.1119, 0.1044],
        [0.1076, 0.1074, 0.1127,  ..., 0.0990, 0.1076, 0.0822],
        [0.0761, 0.1066, 0.1118,  ..., 0.0906, 0.1314,

In [23]:
real_output = F.softmax(output, dim = 1)

In [24]:
real_output

tensor([[0.1261, 0.1123, 0.0860,  ..., 0.1182, 0.0984, 0.0821],
        [0.0896, 0.0902, 0.1129,  ..., 0.0869, 0.0948, 0.0821],
        [0.1094, 0.0999, 0.0819,  ..., 0.1076, 0.1028, 0.0998],
        ...,
        [0.0956, 0.1159, 0.1017,  ..., 0.0664, 0.1152, 0.1304],
        [0.1211, 0.1268, 0.1268,  ..., 0.0938, 0.1119, 0.0802],
        [0.0949, 0.0903, 0.0907,  ..., 0.1042, 0.0957, 0.1325]],
       grad_fn=<SoftmaxBackward>)

In [25]:
print(torch.sum(real_output[:5]).item())

5.0


In [26]:
best_prob, pred = torch.max(real_output, dim = 1)
# print(best_prob)
print(pred[:50])
print("REAL LABELS")
print(label[:50])

tensor([0, 3, 3, 0, 1, 3, 8, 3, 3, 0, 5, 1, 0, 3, 3, 3, 2, 9, 3, 3, 3, 1, 8, 8,
        9, 0, 2, 8, 3, 3, 2, 3, 7, 8, 2, 9, 3, 8, 8, 1, 3, 3, 0, 1, 3, 3, 5, 9,
        3, 2])
REAL LABELS
tensor([2, 3, 7, 6, 8, 8, 4, 5, 1, 2, 2, 9, 3, 1, 2, 8, 7, 7, 1, 0, 2, 6, 2, 7,
        4, 9, 6, 4, 9, 8, 2, 8, 5, 2, 6, 9, 8, 6, 4, 6, 5, 8, 1, 0, 1, 7, 3, 1,
        1, 6])


In [54]:
#creating evaluation metric and loss function
def accuracy(predicted, actual_label):
    return torch.sum(predicted == actual_label).item() / len(predicted)

accuracy(pred, label)


0.122

In [115]:

def loss_fn(pred, label):
    loss_fn  = F.cross_entropy
    loss = loss_fn(pred, label)
    return loss

In [116]:
optim = torch.optim.SGD(model.parameters(), lr = 0.002)

In [133]:
# Training
def train_loss(model, loss_fn,  train_dl, optimizer = None, metric = None):
    for image, label in data_dl:
        pred = model(image)
        loss = loss_fn(pred, label)
        real_output = F.softmax(pred)
        best_prob, pred = torch.max(real_output, dim = 1)
        
        if optimizer is not None:
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()

        metric_result = None
        if metric is not None:
            metric_result = metric(pred, label)

        return loss.item(), len(image), metric_result



In [134]:
train_loss(model, loss_fn,  train_data, optimizer = optim, metric = accuracy)

ipykernel_launcher:6: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


(1.7305145263671875, 500, 0.728)

In [ ]:
def val_loss(model, loss_fn, val_dl, metric = None):
    losses = []

    with torch.no_grad():
        for image, label in val_dl:
            pred = model(pred)
            loss = loss_fn(pred, label)
            losses.append(loss)
            real_output = F.softmax(pred)
            best_prob, pred = torch.max(real_output, dim = 1)

            metric_result = None
            if metric is not None:
                metric_result = metric(pred, label)

            return loss.item(), len(image), metric_result
