In [33]:
import numpy as np
import torch
import torchvision
import torch.nn as nn
import torch.nn.functional as F
from torchvision import transforms
from torchvision.datasets import MNIST
from torch.utils.data.dataloader import DataLoader
from torch.utils.data.sampler import SubsetRandomSampler

In [2]:
datasets = MNIST(root = 'classification data/', download = True)

In [3]:
datasets = MNIST(root = 'classification data/', train = True)

In [4]:
len(datasets)

60000

In [5]:
test_data = MNIST(root = 'classification data/', train = False)

In [6]:
len(test_data)

10000

In [7]:
datasets[2]

(<PIL.Image.Image image mode=L size=28x28 at 0x22453432688>, 4)

In [8]:
test_data[200]

(<PIL.Image.Image image mode=L size=28x28 at 0x22453426388>, 3)

In [9]:
datasets = MNIST(root = 'classification data/', train = True, transform = transforms.ToTensor())

In [10]:
img, label = datasets[2]
print(img.shape)
print(label)

torch.Size([1, 28, 28])
4


In [11]:
test_data = MNIST(root = 'classification data/', train = False, transform = transforms.ToTensor())

In [12]:
img, label = datasets[200]
print(img.shape)
print(label)

torch.Size([1, 28, 28])
1


In [13]:
# creating training datasets and validation datasets
def indices_selector(factor, data_num):
    val_num_of_indices = int(factor * data_num)
    total_indices = np.random.permutation(data_num)
    return total_indices[val_num_of_indices:], total_indices[:val_num_of_indices]

In [14]:
indices_selector(0.2, len(datasets))

(array([33827, 59917, 17196, ..., 25891, 42847, 43229]),
 array([ 6583, 57393, 20074, ..., 14074,  4434, 32080]))

In [15]:
train_indices, val_indices = indices_selector(0.2, len(datasets))

In [16]:
batch_size = 500

In [17]:
train_sampler = SubsetRandomSampler(train_indices)
train_data = DataLoader(datasets, batch_size, sampler = train_sampler)
val_sampler = SubsetRandomSampler(val_indices)
val_data = DataLoader(datasets, batch_size, sampler = val_sampler)

In [18]:
for x, y in train_data:
    print(x.shape)
#     print(y)
print(x)

torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([500, 1, 28, 28])
torch.Size([50

In [19]:
input_size = 28*28
ouput_classes = 10

In [20]:
class MNIST_Classifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(input_size, ouput_classes)
        
    def forward(self, input_reshape):
        input_reshape = input_reshape.reshape(-1, 28*28)
        output = self.linear(input_reshape)
        return output

In [21]:
model = MNIST_Classifier()

In [49]:
for image, label in train_data:
    output = model(image)
    print(output[:2])
    real_output = F.softmax(output, dim = 1)
    print(real_output)
    print(output.shape)

tensor([[ 0.0738,  0.2946,  0.0944, -0.2474,  0.3404, -0.0557,  0.0462, -0.2513,
         -0.1643, -0.1846],
        [-0.0133,  0.2188,  0.0323, -0.0932,  0.3326, -0.0467, -0.1402, -0.0230,
         -0.0063,  0.1164]], grad_fn=<SliceBackward>)
tensor([[0.1060, 0.1322, 0.1082,  ..., 0.0766, 0.0836, 0.0819],
        [0.0941, 0.1187, 0.0985,  ..., 0.0932, 0.0948, 0.1071],
        [0.1004, 0.1234, 0.0843,  ..., 0.1041, 0.0895, 0.0942],
        ...,
        [0.1110, 0.1214, 0.0733,  ..., 0.1072, 0.1026, 0.0853],
        [0.1013, 0.1100, 0.1056,  ..., 0.0882, 0.1068, 0.0959],
        [0.1050, 0.0817, 0.0996,  ..., 0.1000, 0.0949, 0.1087]],
       grad_fn=<SoftmaxBackward>)
torch.Size([500, 10])
tensor([[-0.0965,  0.1519, -0.0922,  0.0370,  0.5000,  0.0106, -0.0523, -0.1819,
         -0.0684, -0.1663],
        [ 0.4531, -0.1199,  0.0125,  0.3736,  0.4315,  0.2611,  0.2967, -0.0132,
          0.3530, -0.0485]], grad_fn=<SliceBackward>)
tensor([[0.0886, 0.1136, 0.0890,  ..., 0.0814, 0.0912, 0.0

       grad_fn=<SoftmaxBackward>)
torch.Size([500, 10])
tensor([[ 0.0861,  0.5707, -0.0086,  0.1599,  0.3612, -0.1216, -0.0420, -0.5008,
          0.1576, -0.2172],
        [ 0.2071,  0.2120, -0.0577,  0.2373,  0.1469,  0.0443, -0.1969, -0.1242,
         -0.1110,  0.0251]], grad_fn=<SliceBackward>)
tensor([[0.1001, 0.1626, 0.0911,  ..., 0.0557, 0.1076, 0.0739],
        [0.1171, 0.1177, 0.0898,  ..., 0.0841, 0.0852, 0.0976],
        [0.1113, 0.1139, 0.1017,  ..., 0.0747, 0.1116, 0.0914],
        ...,
        [0.0912, 0.1081, 0.0861,  ..., 0.0770, 0.1023, 0.0706],
        [0.1026, 0.1186, 0.0745,  ..., 0.1057, 0.0889, 0.0636],
        [0.0771, 0.1321, 0.0852,  ..., 0.0839, 0.0938, 0.0926]],
       grad_fn=<SoftmaxBackward>)
torch.Size([500, 10])
tensor([[ 0.0525,  0.2303, -0.0615, -0.0122, -0.0008,  0.0095,  0.0003, -0.1396,
         -0.0023,  0.0849],
        [-0.2267,  0.1511, -0.1147,  0.1371,  0.2538, -0.2104, -0.1314,  0.0373,
         -0.0762, -0.1031]], grad_fn=<SliceBackward>)
te

       grad_fn=<SoftmaxBackward>)
torch.Size([500, 10])
tensor([[ 0.4061, -0.2371, -0.1492,  0.3496,  0.0798,  0.1083, -0.0906, -0.2507,
         -0.0759,  0.0333],
        [-0.0275,  0.0518, -0.1432,  0.0466,  0.1629,  0.0387, -0.3397, -0.0579,
         -0.0843,  0.0085]], grad_fn=<SliceBackward>)
tensor([[0.1441, 0.0757, 0.0827,  ..., 0.0747, 0.0890, 0.0992],
        [0.0999, 0.1081, 0.0890,  ..., 0.0969, 0.0944, 0.1035],
        [0.0872, 0.1498, 0.0870,  ..., 0.0737, 0.0971, 0.0817],
        ...,
        [0.0861, 0.1053, 0.0612,  ..., 0.0684, 0.1026, 0.0754],
        [0.1132, 0.0979, 0.0810,  ..., 0.0992, 0.0876, 0.0842],
        [0.1022, 0.1172, 0.1034,  ..., 0.0878, 0.0722, 0.0948]],
       grad_fn=<SoftmaxBackward>)
torch.Size([500, 10])
tensor([[-0.0545,  0.2149, -0.1155,  0.0337,  0.1470, -0.0887, -0.1873, -0.0547,
         -0.1793, -0.3560],
        [ 0.0712,  0.1602, -0.1070,  0.1593,  0.1348, -0.0460, -0.1697, -0.0513,
          0.0212, -0.1209]], grad_fn=<SliceBackward>)
te

       grad_fn=<SoftmaxBackward>)
torch.Size([500, 10])
tensor([[-0.0067,  0.0775,  0.3089,  0.1007,  0.4229, -0.2136,  0.1438, -0.2053,
         -0.1350,  0.0954],
        [ 0.2055,  0.1199,  0.0930,  0.2397,  0.3228, -0.0961,  0.1731,  0.0220,
         -0.0455,  0.0546]], grad_fn=<SliceBackward>)
tensor([[0.0918, 0.0999, 0.1259,  ..., 0.0753, 0.0808, 0.1017],
        [0.1093, 0.1003, 0.0977,  ..., 0.0910, 0.0850, 0.0940],
        [0.0941, 0.1048, 0.0822,  ..., 0.0944, 0.0969, 0.0856],
        ...,
        [0.0928, 0.0982, 0.1031,  ..., 0.0788, 0.1148, 0.1124],
        [0.0950, 0.1098, 0.0836,  ..., 0.0972, 0.0921, 0.0918],
        [0.0954, 0.0974, 0.0799,  ..., 0.0678, 0.1116, 0.0703]],
       grad_fn=<SoftmaxBackward>)
torch.Size([500, 10])
tensor([[ 0.0056,  0.0771,  0.1215, -0.1604,  0.0158, -0.1473, -0.1057,  0.0990,
          0.1061, -0.1458],
        [ 0.0154,  0.1097, -0.2155,  0.0377,  0.3872, -0.1266, -0.2320, -0.0210,
          0.0346,  0.0095]], grad_fn=<SliceBackward>)
te

       grad_fn=<SoftmaxBackward>)
torch.Size([500, 10])
tensor([[ 0.0630,  0.3207, -0.0301, -0.2759,  0.0081, -0.1780, -0.0569,  0.0058,
         -0.1636,  0.2597],
        [ 0.1426, -0.0262, -0.1770,  0.0742,  0.3155,  0.2595, -0.0812, -0.3350,
          0.0875, -0.0662]], grad_fn=<SliceBackward>)
tensor([[0.1053, 0.1363, 0.0959,  ..., 0.0995, 0.0840, 0.1282],
        [0.1112, 0.0939, 0.0808,  ..., 0.0690, 0.1052, 0.0902],
        [0.1026, 0.1120, 0.0746,  ..., 0.1005, 0.0926, 0.0712],
        ...,
        [0.1032, 0.0965, 0.1027,  ..., 0.0868, 0.0878, 0.1071],
        [0.0853, 0.0859, 0.0966,  ..., 0.0827, 0.0872, 0.1210],
        [0.1095, 0.1076, 0.0862,  ..., 0.0907, 0.0965, 0.0921]],
       grad_fn=<SoftmaxBackward>)
torch.Size([500, 10])
tensor([[-0.0079,  0.3036, -0.1838,  0.0110,  0.3561, -0.0371,  0.1767, -0.0412,
         -0.0601, -0.1446],
        [ 0.1379,  0.0805, -0.0453, -0.1099,  0.2436,  0.1239, -0.0092, -0.2956,
          0.0785,  0.0207]], grad_fn=<SliceBackward>)
te

       grad_fn=<SoftmaxBackward>)
torch.Size([500, 10])
tensor([[ 0.0935, -0.0458,  0.0055,  0.1161,  0.1775,  0.3728, -0.0347, -0.3028,
          0.1848,  0.0533],
        [ 0.1818, -0.0560, -0.0795,  0.1346,  0.2578, -0.0405,  0.0529, -0.3092,
         -0.0984,  0.1357]], grad_fn=<SliceBackward>)
tensor([[0.1018, 0.0885, 0.0932,  ..., 0.0685, 0.1115, 0.0977],
        [0.1164, 0.0917, 0.0896,  ..., 0.0712, 0.0879, 0.1111],
        [0.1010, 0.1425, 0.0887,  ..., 0.0868, 0.1146, 0.0826],
        ...,
        [0.1015, 0.1116, 0.1075,  ..., 0.0884, 0.0772, 0.1093],
        [0.1043, 0.1095, 0.0686,  ..., 0.0873, 0.0948, 0.0707],
        [0.0920, 0.1498, 0.0905,  ..., 0.0649, 0.0957, 0.0750]],
       grad_fn=<SoftmaxBackward>)
torch.Size([500, 10])
tensor([[-0.1908,  0.3265,  0.1477,  0.1256,  0.2453, -0.2467, -0.2769, -0.4269,
         -0.0405, -0.0492],
        [ 0.3968, -0.1530, -0.2385,  0.1530,  0.4380,  0.3384, -0.2068, -0.2281,
          0.3406, -0.1156]], grad_fn=<SliceBackward>)
te

       grad_fn=<SoftmaxBackward>)
torch.Size([500, 10])
tensor([[-0.0245,  0.1540, -0.1255,  0.0486,  0.2379, -0.0556,  0.0210,  0.0929,
          0.0277,  0.1740],
        [-0.0967,  0.1366,  0.1027,  0.0554,  0.3656, -0.2547,  0.2818, -0.0103,
         -0.0333,  0.2585]], grad_fn=<SliceBackward>)
tensor([[0.0918, 0.1098, 0.0830,  ..., 0.1033, 0.0968, 0.1120],
        [0.0824, 0.1041, 0.1006,  ..., 0.0899, 0.0878, 0.1176],
        [0.0952, 0.1129, 0.1012,  ..., 0.0877, 0.0965, 0.1138],
        ...,
        [0.1055, 0.1052, 0.1137,  ..., 0.0778, 0.1032, 0.1120],
        [0.1053, 0.1213, 0.0895,  ..., 0.1024, 0.0895, 0.0706],
        [0.1100, 0.0884, 0.0838,  ..., 0.0974, 0.0917, 0.0895]],
       grad_fn=<SoftmaxBackward>)
torch.Size([500, 10])
tensor([[ 0.2004, -0.0138, -0.1157,  0.0064,  0.2495, -0.0957,  0.0336, -0.1698,
          0.0619, -0.1037],
        [ 0.0230,  0.4096, -0.0988,  0.0592,  0.2534, -0.3048, -0.2082, -0.0989,
         -0.0074, -0.1743]], grad_fn=<SliceBackward>)
te

       grad_fn=<SoftmaxBackward>)
torch.Size([500, 10])
tensor([[ 0.1216,  0.1418, -0.1750,  0.1797,  0.3765, -0.0505, -0.2054, -0.1541,
          0.0922,  0.0147],
        [ 0.0240,  0.2448, -0.2491,  0.1587,  0.5046,  0.1496, -0.2065,  0.1684,
         -0.0474, -0.2010]], grad_fn=<SliceBackward>)
tensor([[0.1075, 0.1097, 0.0799,  ..., 0.0816, 0.1043, 0.0966],
        [0.0945, 0.1178, 0.0719,  ..., 0.1092, 0.0880, 0.0755],
        [0.0781, 0.1327, 0.1072,  ..., 0.0737, 0.1023, 0.0851],
        ...,
        [0.1155, 0.1218, 0.0855,  ..., 0.0686, 0.0819, 0.0775],
        [0.0980, 0.1434, 0.0944,  ..., 0.0863, 0.0998, 0.1018],
        [0.0907, 0.1203, 0.0782,  ..., 0.0776, 0.0994, 0.0772]],
       grad_fn=<SoftmaxBackward>)
torch.Size([500, 10])
tensor([[-0.1532,  0.1011, -0.2302,  0.2014,  0.3557, -0.1027,  0.1255, -0.0833,
         -0.1348, -0.1429],
        [ 0.1849,  0.0496, -0.0975, -0.0021,  0.3270,  0.0040, -0.1286, -0.0060,
         -0.1392, -0.4181]], grad_fn=<SliceBackward>)
te

       grad_fn=<SoftmaxBackward>)
torch.Size([500, 10])


In [35]:
help(F)

Help on module torch.nn.functional in torch.nn:

NAME
    torch.nn.functional - Functional interface

FUNCTIONS
    adaptive_avg_pool1d(...)
        adaptive_avg_pool1d(input, output_size) -> Tensor
        
        Applies a 1D adaptive average pooling over an input signal composed of
        several input planes.
        
        See :class:`~torch.nn.AdaptiveAvgPool1d` for details and output shape.
        
        Args:
            output_size: the target output size (single integer)
    
    adaptive_avg_pool2d(input, output_size)
        Applies a 2D adaptive average pooling over an input signal composed of
        several input planes.
        
        See :class:`~torch.nn.AdaptiveAvgPool2d` for details and output shape.
        
        Args:
            output_size: the target output size (single integer or
                double-integer tuple)
    
    adaptive_avg_pool3d(input, output_size)
        Applies a 3D adaptive average pooling over an input signal composed of
     

In [40]:
real_output = F.softmax(output, dim = 1)

In [42]:
real_output

tensor([[0.1137, 0.0879, 0.0755,  ..., 0.0729, 0.0982, 0.0908],
        [0.1123, 0.1183, 0.0955,  ..., 0.0797, 0.1060, 0.0957],
        [0.1223, 0.0823, 0.0996,  ..., 0.0817, 0.0875, 0.1112],
        ...,
        [0.0838, 0.1114, 0.0732,  ..., 0.0831, 0.0978, 0.0628],
        [0.0836, 0.1295, 0.1134,  ..., 0.0666, 0.1259, 0.0715],
        [0.0913, 0.1156, 0.0985,  ..., 0.0709, 0.1166, 0.0761]],
       grad_fn=<SoftmaxBackward>)