In [16]:
import numpy as np
import torch

In [17]:
# temp, rainfall, humidity
features = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [18]:
# apples, orranges
labels = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [19]:
features = torch.from_numpy(features)
labels = torch.from_numpy(labels)

In [110]:
# create weights and biases
w = torch.randn(2, 3, requires_grad = True)
b = torch.randn(2, requires_grad = True)

In [111]:
def model(x):
    return x@w.t() + b

In [112]:
predicted_labels  = model(features)
predicted_labels

tensor([[-147.6239,  102.4226],
        [-180.2327,  134.2563],
        [-159.3153,  158.7074],
        [-227.7659,  101.3593],
        [-121.8470,  129.1789]], grad_fn=<AddBackward0>)

In [113]:
print(labels)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [114]:
#loss function
def loss_fn(t1, t2):
    diff = t1 - t2
    return (torch.sum(diff*diff)/ torch.numel(diff))

In [115]:
loss = loss_fn(predicted_labels, labels)
loss

tensor(30716.7617, grad_fn=<DivBackward0>)

In [116]:
loss.backward()

In [117]:
print(w)
print(w.grad)

tensor([[-2.4739,  0.2775,  0.2902],
        [ 0.5688,  0.6326,  0.3958]], requires_grad=True)
tensor([[-20768.1445, -21250.1562, -13319.5283],
        [  2979.3408,   2457.6555,   1621.4836]])


In [118]:
print(b)
print(b.grad)

tensor([1.8995, 1.4996], requires_grad=True)
tensor([-243.5570,   33.1849])


In [119]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [152]:
epochs = 5
for _ in range(epochs):
    predicted_labels = model(features)
    loss = loss_fn(predicted_labels, labels)
    print(loss)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5 
        w.grad.zero_()
        b.grad.zero_()

tensor(97.6925, grad_fn=<DivBackward0>)
tensor(96.6314, grad_fn=<DivBackward0>)
tensor(95.5833, grad_fn=<DivBackward0>)
tensor(94.5481, grad_fn=<DivBackward0>)
tensor(93.5258, grad_fn=<DivBackward0>)


In [153]:
predicted_labels

tensor([[ 54.0857,  73.2217],
        [ 81.3135,  98.7823],
        [125.6817, 132.5742],
        [  1.4400,  52.1017],
        [112.2060, 107.3446]], grad_fn=<AddBackward0>)

In [154]:
labels

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])