In [69]:
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import torch.nn.functional as F

In [36]:
# temp, rainfall, humidity
features = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [37]:
# apples, orranges
labels = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [38]:
features = torch.from_numpy(features)
labels = torch.from_numpy(labels)

In [5]:
# create weights and biases
w = torch.randn(2, 3, requires_grad = True)
b = torch.randn(2, requires_grad = True)

In [6]:
def model(x):
    return x@w.t() + b

In [7]:
predicted_labels  = model(features)
predicted_labels

tensor([[ 36.4604, -11.2929],
        [ 54.1645, -10.3464],
        [ 50.1487, -30.0884],
        [ 31.2684,  -9.7082],
        [ 59.0841,  -6.9797]], grad_fn=<AddBackward0>)

In [8]:
print(labels)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [9]:
#loss function
def loss_fn(t1, t2):
    diff = t1 - t2
    return (torch.sum(diff*diff)/ torch.numel(diff))

In [10]:
loss = loss_fn(predicted_labels, labels)
loss

tensor(7151.3877, grad_fn=<DivBackward0>)

In [11]:
loss.backward()

In [12]:
print(w)
print(w.grad)

tensor([[ 0.0066,  0.0199,  0.8175],
        [-0.1414, -0.3713,  0.5376]], requires_grad=True)
tensor([[ -2388.6609,  -3342.8281,  -1856.4468],
        [ -8742.4873, -10240.2920,  -6125.5352]])


In [13]:
print(b)
print(b.grad)

tensor([-0.5060,  0.7933], requires_grad=True)
tensor([ -29.9748, -105.6831])


In [14]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [15]:
# Training
epochs = 5
for _ in range(epochs):
    predicted_labels = model(features)
    loss = loss_fn(predicted_labels, labels)
    print(loss)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5 
        w.grad.zero_()
        b.grad.zero_()

tensor(7151.3877, grad_fn=<DivBackward0>)
tensor(4973.4575, grad_fn=<DivBackward0>)
tensor(3503.8530, grad_fn=<DivBackward0>)
tensor(2511.6042, grad_fn=<DivBackward0>)
tensor(1841.0621, grad_fn=<DivBackward0>)


In [16]:
predicted_labels

tensor([[50.9980, 37.0614],
        [73.3470, 53.2889],
        [73.5509, 45.8923],
        [44.9499, 37.5612],
        [77.9249, 54.5283]], grad_fn=<AddBackward0>)

In [17]:
labels

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

# In-Built Linear R

In [40]:
# Input (temp, rainfall, humidity)
features = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')


In [45]:
# Targets (apples, oranges)
labels = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

In [46]:
features = torch.from_numpy(features)
labels = torch.from_numpy(labels)

In [48]:
data = TensorDataset(features, labels)

In [49]:
train_data = DataLoader(data, batch_size = 2, shuffle = True)

In [53]:
for x, y in train_data:
    print(x, y)

tensor([[103.,  43.,  36.],
        [ 92.,  87.,  64.]]) tensor([[ 20.,  38.],
        [ 82., 100.]])
tensor([[73., 67., 43.],
        [68., 97., 70.]]) tensor([[ 56.,  70.],
        [102., 120.]])
tensor([[ 69.,  96.,  70.],
        [ 87., 134.,  58.]]) tensor([[103., 119.],
        [119., 133.]])
tensor([[91., 87., 65.],
        [74., 66., 43.]]) tensor([[ 80., 102.],
        [ 57.,  69.]])
tensor([[101.,  44.,  37.],
        [ 87., 135.,  57.]]) tensor([[ 21.,  38.],
        [118., 134.]])
tensor([[102.,  43.,  37.],
        [ 68.,  96.,  71.]]) tensor([[ 22.,  37.],
        [104., 118.]])
tensor([[ 91.,  88.,  64.],
        [ 88., 134.,  59.]]) tensor([[ 81., 101.],
        [118., 132.]])
tensor([[73., 66., 44.]]) tensor([[57., 69.]])


In [56]:
model = nn.Linear(3,2)

In [61]:
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.5448,  0.1519, -0.5098],
        [ 0.3099, -0.1812, -0.5044]], requires_grad=True)
Parameter containing:
tensor([-0.3378,  0.2345], requires_grad=True)


In [63]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.5448,  0.1519, -0.5098],
         [ 0.3099, -0.1812, -0.5044]], requires_grad=True),
 Parameter containing:
 tensor([-0.3378,  0.2345], requires_grad=True)]

In [73]:
# make prediction
predicted_labels = model(features)
predicted_labels

tensor([[-51.8546, -10.9717],
        [-69.1771, -19.7907],
        [-56.9525, -26.3389],
        [-68.2417,   5.3903],
        [-59.0340, -31.0842],
        [-52.5513, -10.4806],
        [-69.8387, -20.1139],
        [-58.0071, -26.5334],
        [-67.5450,   4.8992],
        [-58.9989, -31.8985],
        [-52.5163, -11.2948],
        [-69.8738, -19.2996],
        [-56.2908, -26.0157],
        [-68.2768,   6.2046],
        [-58.3373, -31.5753]], grad_fn=<AddmmBackward>)

In [66]:
labels

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [75]:
# loss function
loss_fn = F.mse_loss
loss = loss_fn(predicted_labels, labels)

In [83]:
#optimizer
optimizer = torch.optim.Adam(model.parameters(), lr = 1e-5)