In [1]:
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import torch.nn.functional as F

In [2]:
# temp, rainfall, humidity
features = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
# apples, orranges
labels = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
features = torch.from_numpy(features)
labels = torch.from_numpy(labels)

In [5]:
# create weights and biases
w = torch.randn(2, 3, requires_grad = True)
b = torch.randn(2, requires_grad = True)

In [6]:
def model(x):
    return x@w.t() + b

In [7]:
predicted_labels  = model(features)
predicted_labels

tensor([[-164.4285,  -99.1073],
        [-206.9816, -134.1853],
        [-187.5201, -142.1649],
        [-234.4945, -100.5238],
        [-156.1264, -130.9910]], grad_fn=<AddBackward0>)

In [8]:
print(labels)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [9]:
#loss function
def loss_fn(t1, t2):
    diff = t1 - t2
    return (torch.sum(diff*diff)/ torch.numel(diff))

In [10]:
loss = loss_fn(predicted_labels, labels)
loss

tensor(59944.6133, grad_fn=<DivBackward0>)

In [11]:
loss.backward()

In [12]:
print(w)
print(w.grad)

tensor([[-2.3075,  0.1912, -0.2397],
        [-0.5116, -0.3349, -0.8969]], requires_grad=True)
tensor([[-22601.4062, -23418.0371, -14663.3125],
        [-17792.5703, -19762.2500, -12174.1582]])


In [13]:
print(b)
print(b.grad)

tensor([ 1.5143, -0.7511], requires_grad=True)
tensor([-266.1103, -213.3945])


In [14]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [15]:
# Training
epochs = 5
for _ in range(epochs):
    predicted_labels = model(features)
    loss = loss_fn(predicted_labels, labels)
    print(loss)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5 
        w.grad.zero_()
        b.grad.zero_()

tensor(59944.6133, grad_fn=<DivBackward0>)
tensor(40554.3086, grad_fn=<DivBackward0>)
tensor(27485.7070, grad_fn=<DivBackward0>)
tensor(18677.2188, grad_fn=<DivBackward0>)
tensor(12739.5908, grad_fn=<DivBackward0>)


In [16]:
predicted_labels

tensor([[ -47.0480,   -3.2319],
        [ -52.8345,   -8.0910],
        [  -6.1548,    7.3548],
        [-116.7452,   -5.7648],
        [  -8.8612,   -9.6824]], grad_fn=<AddBackward0>)

In [17]:
labels

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

# In-Built Linear R

In [18]:
# Input (temp, rainfall, humidity)
features = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')


In [19]:
# Targets (apples, oranges)
labels = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

In [20]:
features = torch.from_numpy(features)
labels = torch.from_numpy(labels)

In [21]:
data = TensorDataset(features, labels)

In [42]:
train_data = DataLoader(data, batch_size = 5, shuffle = True)

In [ ]:
for x, y in train_data:
    print(x, y)

In [55]:
model = nn.Linear(3,2)

In [ ]:
print(model.weight)
print(model.bias)

In [ ]:
list(model.parameters())

In [24]:
# make prediction
predicted_labels = model(features)
predicted_labels

tensor([[-3.3357, 36.7248],
        [-4.8762, 51.1308],
        [ 1.4211, 50.5129],
        [-7.7505, 36.9083],
        [-2.8655, 51.0438],
        [-3.5320, 36.8206],
        [-5.1083, 51.5525],
        [ 1.2216, 51.1580],
        [-7.5542, 36.8125],
        [-2.9012, 51.3698],
        [-3.5677, 37.1465],
        [-5.0725, 51.2266],
        [ 1.6532, 50.0912],
        [-7.7147, 36.5823],
        [-2.6692, 50.9481]], grad_fn=<AddmmBackward>)

In [ ]:
labels

In [ ]:
# loss function
loss_fn = F.mse_loss
loss = loss_fn(predicted_labels, labels)

In [78]:
model = nn.Linear(3,2)

In [79]:
#optimizer
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-6)

In [80]:
def fit(num_of_epochs, loss_fn, optimizer):
    for epoch in range(num_of_epochs):
        for x,y in train_data:
            predicted_label = model(x)
            loss = loss_fn(predicted_label, y)
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()

        if (epoch + 1) % 10 == 0:
            print('Epoch {}/{} : Loss = {:4f}'.format((epoch+1), num_of_epochs, loss.item()))

In [81]:
fit(100, loss_fn, optimizer)

Epoch 10/100 : Loss = 2105.496582
Epoch 20/100 : Loss = 1017.247681
Epoch 30/100 : Loss = 640.152954
Epoch 40/100 : Loss = 828.310425
Epoch 50/100 : Loss = 973.517273
Epoch 60/100 : Loss = 317.852722
Epoch 70/100 : Loss = 420.593597
Epoch 80/100 : Loss = 761.630127
Epoch 90/100 : Loss = 765.332886
Epoch 100/100 : Loss = 359.031250
